#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: person-register

#server port

server:
    port: 8089

#keycloak configurations
keycloak:
  realm: INFOINS
  auth-server-url: http://52.230.11.5:8080/auth
  ssl-required: external
  resource: enic-admin-service
  bearer-only: true
  credentials.secret: 3d882d99-b372-49bb-8b0e-88592a880f25

  security-constraints[0]:
    authRoles[0]: super-admin
    securityCollections[0]:
      patterns[0]: /province/*
      patterns[1]: /district/*
      patterns[2]: /secretariat/*

keycloakProxy:
  login-url: /realms/INFOINS/protocol/openid-connect/token
  userinfo-url: /realms/INFOINS/protocol/openid-connect/userinfo
  client-id: curl
  grant-type: password